In [41]:
import torch as torch
import pandas as pd
import glob as glob
import matplotlib as plt
import numpy as np
from torch_geometric.data import Data
from sklearn.preprocessing import StandardScaler

from numpy.ma.extras import average
from six import print_
from torch_geometric.utils import is_undirected

In [42]:
# loading dataframe
path = r'C:\Users\hkute\Documents\LearningPython\tennis_predictor\Tennis_Predictor\datasets'

all_files = glob.glob(path + r"\atp_matches_*.csv")

df = pd.concat((pd.read_csv(f) for f in all_files), ignore_index=True)

pd.set_option('display.max_columns', None)

df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2003-1536,Madrid Masters,Hard,48,M,20031013,1,101965,NaN,NaN,Wayne Ferreira,R,185.0,RSA,32.0,103344,NaN,NaN,Ivan Ljubicic,R,193.0,CRO,24.5,7-6(7) 7-6(5),3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,1090.0,42.0,865.0
1,2003-1536,Madrid Masters,Hard,48,M,20031013,2,102358,NaN,Q,Thomas Enqvist,R,190.0,SWE,29.5,102338,NaN,NaN,Yevgeny Kafelnikov,R,190.0,RUS,29.6,6-3 RET,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.0,258.0,40.0,950.0
2,2003-1536,Madrid Masters,Hard,48,M,20031013,3,102998,NaN,Q,Jan Michael Gambill,R,190.0,USA,26.3,103786,NaN,NaN,Nikolay Davydenko,R,178.0,RUS,22.3,6-3 6-3,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,660.0,43.0,855.0
3,2003-1536,Madrid Masters,Hard,48,M,20031013,4,102610,NaN,NaN,Albert Costa,R,180.0,ESP,28.3,103602,NaN,NaN,Fernando Gonzalez,R,183.0,CHI,23.2,6-3 7-6(3),3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,1170.0,22.0,1190.0
4,2003-1536,Madrid Masters,Hard,48,M,20031013,5,102374,NaN,WC,Alex Corretja,R,180.0,ESP,29.5,104745,NaN,WC,Rafael Nadal,L,185.0,ESP,17.3,6-2 3-6 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.0,290.0,49.0,788.0

We will drop some columns

There are missing values which we will need for later on

In [43]:
df.drop(['winner_seed', 'loser_seed','loser_entry', 'winner_entry'], axis=1, inplace=True)
df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2003-1536,Madrid Masters,Hard,48,M,20031013,1,101965,Wayne Ferreira,R,185.0,RSA,32.0,103344,Ivan Ljubicic,R,193.0,CRO,24.5,7-6(7) 7-6(5),3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,1090.0,42.0,865.0
1,2003-1536,Madrid Masters,Hard,48,M,20031013,2,102358,Thomas Enqvist,R,190.0,SWE,29.5,102338,Yevgeny Kafelnikov,R,190.0,RUS,29.6,6-3 RET,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.0,258.0,40.0,950.0
2,2003-1536,Madrid Masters,Hard,48,M,20031013,3,102998,Jan Michael Gambill,R,190.0,USA,26.3,103786,Nikolay Davydenko,R,178.0,RUS,22.3,6-3 6-3,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,660.0,43.0,855.0
3,2003-1536,Madrid Masters,Hard,48,M,20031013,4,102610,Albert Costa,R,180.0,ESP,28.3,103602,Fernando Gonzalez,R,183.0,CHI,23.2,6-3 7-6(3),3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,1170.0,22.0,1190.0
4,2003-1536,Madrid Masters,Hard,48,M,20031013,5,102374,Alex Corretja,R,180.0,ESP,29.5,104745,Rafael Nadal,L,185.0,ESP,17.3,6-2 3-6 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.0,290.0,49.0,788.0

In [44]:
df = df.fillna(df.mean(numeric_only=True))
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2003-1536,Madrid Masters,Hard,48,M,20031013,1,101965,Wayne Ferreira,R,185.000000,RSA,32.0,103344,Ivan Ljubicic,R,193.000000,CRO,24.500000,7-6(7) 7-6(5),3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,28.0,1090.0,42.000000,865.000000
1,2003-1536,Madrid Masters,Hard,48,M,20031013,2,102358,Thomas Enqvist,R,190.000000,SWE,29.5,102338,Yevgeny Kafelnikov,R,190.000000,RUS,29.600000,6-3 RET,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,146.0,258.0,40.000000,950.000000
2,2003-1536,Madrid Masters,Hard,48,M,20031013,3,102998,Jan Michael Gambill,R,190.000000,USA,26.3,103786,Nikolay Davydenko,R,178.000000,RUS,22.300000,6-3 6-3,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,57.0,660.0,43.000000,855.000000
3,2003-1536,Madrid Masters,Hard,48,M,20031013,4,102610,Albert Costa,R,180.000000,ESP,28.3,103602,Fernando Gonzalez,R,183.000000,CHI,23.200000,6-3 7-6(3),3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,23.0,1170.0,22.000000,1190.000000
4,2003-1536,Madrid Masters,Hard,48,M,20031013,5,102374,Alex Corretja,R,180.000000,ESP,29.5,104745,Rafael Nadal,L,185.000000,ESP,17.300000,6-2 3-6 6-4,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,127.0,290.0,49.000000,788.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436092,2024-8268,Yokkaichi CH,Hard,32,C,20241125,342,122352,Christoph Negritu,R,193.000000,GER,30.6,206923,Shinji Hazawa,R,175.000000,JPN,25.600000,7-5 6-3,3,Q1,95.000000,5.000000,1.000000,68.000000,39.000000,25.000000,19.000000,11.000000,3.000000,5.000000,0.000000,0.000000,73.000000,54.00000,29.000000,9.000000,10.000000,5.000000,9.000000,409.0,113.0,1073.000000,11.000000
436093,2024-8268,Yokkaichi CH,Hard,32,C,20241125,341,207987,Ryuki Matsuda,R,157.000000,JPN,24.9,200665,Yuta Kawahashi,R,175.000000,JPN,26.800000,6-4 6-0,3,Q1,69.000000,1.000000,0.000000,51.000000,28.000000,20.000000,16.000000,8.000000,5.000000,5.000000,0.000000,1.000000,54.000000,31.00000,16.000000,10.000000,8.000000,4.000000,8.000000,507.0,76.0,860.000000,22.000000
436094,2024-8268,Yokkaichi CH,Hard,32,C,20241125,340,209951,Petr Bar Biryukov,L,196.000000,RUS,22.7,202356,Tsung Hao Huang,R,173.000000,TPE,25.000000,6-4 6-3,3,Q1,67.000000,4.000000,2.000000,62.000000,35.000000,28.000000,7.000000,9.000000,5.000000,8.000000,0.000000,5.000000,66.000000,41.00000,22.000000,8.000000,10.000000,4.000000,10.000000,429.0,100.0,708.000000,40.000000
436095,2024-8268,Yokkaichi CH,Hard,32,C,20241125,338,202113,Hikaru Shiraishi,R,168.000000,JPN,24.5,211627,Hayato Matsuoka,R,180.000000,JPN,19.800000,7-6(6) 3-6 6-4,3,Q1,180.000000,1.000000,2.000000,93.000000,53.000000,29.000000,22.000000,15.000000,2.000000,7.000000,2.000000,1.000000,117.000000,68.00000,41.000000,23.000000,16.000000,7.000000,12.000000,528.0,71.0,894.000000,20.000000
436096,2024-8268,Yokkaichi CH,Hard,32,C,20241125,337,211774,Ryotaro Taguchi,U,184.539816,JPN,24.4,211548,Shion Motoyama,U,184.362947,JPN,23.974296,6-1 6-2,3,Q1,58.000000,0.000000,1.000000,43.000000,26.000000,21.000000,13.000000,8.000000,2.000000,2.000000,1.000000,2.000000,42.000000,26.00000,11.000000,7.000000,7.000000,4.000000,8.000000,545.0,67.0,629.089681,247.785546

In [45]:
# one hot encoding surface
surface = pd.get_dummies(df.surface, dtype=int)

df = pd.concat([df, surface], axis='columns')
df.drop(["surface"], axis='columns', inplace=True)

df

,tourney_id,tourney_name,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,Carpet,Clay,Grass,Hard
0,2003-1536,Madrid Masters,48,M,20031013,1,101965,Wayne Ferreira,R,185.000000,RSA,32.0,103344,Ivan Ljubicic,R,193.000000,CRO,24.500000,7-6(7) 7-6(5),3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,28.0,1090.0,42.000000,865.000000,0,0,0,1
1,2003-1536,Madrid Masters,48,M,20031013,2,102358,Thomas Enqvist,R,190.000000,SWE,29.5,102338,Yevgeny Kafelnikov,R,190.000000,RUS,29.600000,6-3 RET,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,146.0,258.0,40.000000,950.000000,0,0,0,1
2,2003-1536,Madrid Masters,48,M,20031013,3,102998,Jan Michael Gambill,R,190.000000,USA,26.3,103786,Nikolay Davydenko,R,178.000000,RUS,22.300000,6-3 6-3,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,57.0,660.0,43.000000,855.000000,0,0,0,1
3,2003-1536,Madrid Masters,48,M,20031013,4,102610,Albert Costa,R,180.000000,ESP,28.3,103602,Fernando Gonzalez,R,183.000000,CHI,23.200000,6-3 7-6(3),3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,23.0,1170.0,22.000000,1190.000000,0,0,0,1
4,2003-1536,Madrid Masters,48,M,20031013,5,102374,Alex Corretja,R,180.000000,ESP,29.5,104745,Rafael Nadal,L,185.000000,ESP,17.300000,6-2 3-6 6-4,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,127.0,290.0,49.000000,788.000000,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436092,2024-8268,Yokkaichi CH,32,C,20241125,342,122352,Christoph Negritu,R,193.000000,GER,30.6,206923,Shinji Hazawa,R,175.000000,JPN,25.600000,7-5 6-3,3,Q1,95.000000,5.000000,1.000000,68.000000,39.000000,25.000000,19.000000,11.000000,3.000000,5.000000,0.000000,0.000000,73.000000,54.00000,29.000000,9.000000,10.000000,5.000000,9.000000,409.0,113.0,1073.000000,11.000000,0,0,0,1
436093,2024-8268,Yokkaichi CH,32,C,20241125,341,207987,Ryuki Matsuda,R,157.000000,JPN,24.9,200665,Yuta Kawahashi,R,175.000000,JPN,26.800000,6-4 6-0,3,Q1,69.000000,1.000000,0.000000,51.000000,28.000000,20.000000,16.000000,8.000000,5.000000,5.000000,0.000000,1.000000,54.000000,31.00000,16.000000,10.000000,8.000000,4.000000,8.000000,507.0,76.0,860.000000,22.000000,0,0,0,1
436094,2024-8268,Yokkaichi CH,32,C,20241125,340,209951,Petr Bar Biryukov,L,196.000000,RUS,22.7,202356,Tsung Hao Huang,R,173.000000,TPE,25.000000,6-4 6-3,3,Q1,67.000000,4.000000,2.000000,62.000000,35.000000,28.000000,7.000000,9.000000,5.000000,8.000000,0.000000,5.000000,66.000000,41.00000,22.000000,8.000000,10.000000,4.000000,10.000000,429.0,100.0,708.000000,40.000000,0,0,0,1
436095,2024-8268,Yokkaichi CH,32,C,20241125,338,202113,Hikaru Shiraishi,R,168.000000,JPN,24.5,211627,Hayato Matsuoka,R,180.000000,JPN,19.800000,7-6(6) 3-6 6-4,3,Q1,180.000000,1.000000,2.000000,93.000000,53.000000,29.000000,22.000000,15.000000,2.000000,7.000000,2.000000,1.000000,117.000000,68.00000,41.000000,23.000000,16.000000,7.000000,12.000000,528.0,71.0,894.000000,20.000000,0,0,0,1
436096,2024-8268,Yokkaichi CH,32,C,20241125,337,211774,Ryotaro Taguchi,U,184.539816,JPN,24.4,211548,Shion Motoyama,U,184.362947,JPN,23.974296,6-1 6-2,3,Q1,58.000000,0.000000,1.000000,43.000000,26.000000,21.000000,13.000000,8.000000,2.000000,2.000000,1.000000,2.000000,42.000000,26.00000,11.000000,7.000000,7.000000,4.000000,8.000000,545.0,67.0,629.089681,247.785546,0,0,0,1

In [46]:
# separating data to historical and future data
df['tourney_date'] = pd.to_datetime(df['tourney_date'], format='%Y%m%d')

historical_df = df[df['tourney_date'] < "2023-01-01"]
future_df = df[df['tourney_date'] >= "2023-01-01"]

historical_df.head()

,tourney_id,tourney_name,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,Carpet,Clay,Grass,Hard
0,2003-1536,Madrid Masters,48,M,2003-10-13,1,101965,Wayne Ferreira,R,185.0,RSA,32.0,103344,Ivan Ljubicic,R,193.0,CRO,24.5,7-6(7) 7-6(5),3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,28.0,1090.0,42.0,865.0,0,0,0,1
1,2003-1536,Madrid Masters,48,M,2003-10-13,2,102358,Thomas Enqvist,R,190.0,SWE,29.5,102338,Yevgeny Kafelnikov,R,190.0,RUS,29.6,6-3 RET,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,146.0,258.0,40.0,950.0,0,0,0,1
2,2003-1536,Madrid Masters,48,M,2003-10-13,3,102998,Jan Michael Gambill,R,190.0,USA,26.3,103786,Nikolay Davydenko,R,178.0,RUS,22.3,6-3 6-3,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,57.0,660.0,43.0,855.0,0,0,0,1
3,2003-1536,Madrid Masters,48,M,2003-10-13,4,102610,Albert Costa,R,180.0,ESP,28.3,103602,Fernando Gonzalez,R,183.0,CHI,23.2,6-3 7-6(3),3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,23.0,1170.0,22.0,1190.0,0,0,0,1
4,2003-1536,Madrid Masters,48,M,2003-10-13,5,102374,Alex Corretja,R,180.0,ESP,29.5,104745,Rafael Nadal,L,185.0,ESP,17.3,6-2 3-6 6-4,3,R64,100.565826,5.597889,2.571659,72.170873,44.686945,33.278129,15.119164,11.466324,3.345778,4.929678,4.130268,3.327813,74.848836,45.13172,29.365498,13.441081,11.285491,4.553419,8.399145,127.0,290.0,49.0,788.0,0,0,0,1

for Node Features we will combine play results and get an average for each player

In [47]:
# separate winner stats from losers stats
winner_stats = [col for col in historical_df.columns if col.startswith('w_')]
loser_stats = [col for col in historical_df.columns if col.startswith('l_')]

# create winner and loser df
winners = historical_df[['winner_id'] + winner_stats].copy()
winners.columns = ['player_id'] + [col[2:] for col in winner_stats]

losers = historical_df[['loser_id'] + loser_stats].copy()
losers.columns = ['player_id'] + [col[2:] for col in loser_stats]

# combine results
players_df = pd.concat([winners, losers], ignore_index=True)

# get average
player_averages = players_df.groupby('player_id').mean()
player_averages = player_averages.reset_index()

atp_players = pd.read_csv(r'datasets\atp_players.csv', dtype={'wikidata_id':'string'})
#print(atp_players)

atp_players['player_id'] = atp_players['player_id'].astype('Int64')
atp_players['player'] = atp_players['name_first'] + ' ' + atp_players['name_last']


official_df = player_averages.merge(atp_players[['player_id','player','height','dob','hand','ioc']], on='player_id', how='left')
official_df['dob'] = official_df['dob'].astype('Int64')

print(official_df)

       player_id       ace        df       svpt      1stIn     1stWon  \
0         100644  7.575835  3.880909  77.882098  49.684914  36.507129
1         100653  4.130268  3.327813  74.848836  45.131720  29.365498
2         101266  4.130268  3.327813  74.848836  45.131720  29.365498
3         101305  0.000000  5.000000  90.000000  51.000000  31.000000
4         101316  4.130268  3.327813  74.848836  45.131720  29.365498
...          ...       ...       ...        ...        ...        ...
12712     211773  4.130268  3.327813  74.848836  45.131720  29.365498
12713     211774  5.108682  2.823710  73.063527  44.835203  31.973919
12714     211776  2.500000  3.000000  56.500000  35.000000  20.500000
12715     212813  4.130268  3.327813  74.848836  45.131720  29.365498
12716     212814  4.130268  3.327813  74.848836  45.131720  29.365498

          2ndWon      SvGms    bpSaved    bpFaced                  player  \
0      14.191667  12.486935   3.564218   5.884390        Alexander Zverev
1      13.441081  11.285491   4.553419   8.399145            Andres Gomez
2      13.441081  11.285491   4.553419   8.399145             Trey Carter
3      18.000000  10.000000  10.000000  14.000000          Jeff Greenwald
4      13.441081  11.285491   4.553419   8.399145               Juan Rios
...          ...        ...        ...        ...                     ...
12712  13.441081  11.285491   4.553419   8.399145  Mohamed El Hafedh Said
12713  14.559803  11.406046   3.748325   6.086167         Ryotaro Taguchi
12714   7.000000   8.000000   4.500000   9.000000        Martin Landaluce
12715  13.441081  11.285491   4.553419   8.399145          Kentaro Otsuka
12716  13.441081  11.285491   4.553419   8.399145            Naoya KOMODA

       height       dob hand  ioc
0       198.0  19970420    R  GER
1       193.0  19600227    L  ECU
2       188.0  19660702    R  USA
3         NaN  19661110    R  USA
4       185.0  19661215    R  PUR
...       ...       ...  ...  ...
12712     NaN      <NA>    U  MRT
12713     NaN  20000630    U  JPN
12714   191.0  20060108    R  ESP
12715     NaN      <NA>    U  JPN
12716     NaN      <NA>    U  JPN

[12717 rows x 15 columns]

In [48]:
# make sure there is only one player per row
print(max(official_df['player_id'].value_counts()))

1

In [49]:
sorted_df = official_df.sort_values(by='player_id')

sorted_df

,player_id,ace,df,svpt,1stIn,1stWon,2ndWon,SvGms,bpSaved,bpFaced,player,height,dob,hand,ioc
0,100644,7.575835,3.880909,77.882098,49.684914,36.507129,14.191667,12.486935,3.564218,5.884390,Alexander Zverev,198.0,19970420,R,GER
1,100653,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,Andres Gomez,193.0,19600227,L,ECU
2,101266,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,Trey Carter,188.0,19660702,R,USA
3,101305,0.000000,5.000000,90.000000,51.000000,31.000000,18.000000,10.000000,10.000000,14.000000,Jeff Greenwald,NaN,19661110,R,USA
4,101316,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,Juan Rios,185.0,19661215,R,PUR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12712,211773,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,Mohamed El Hafedh Said,NaN,<NA>,U,MRT
12713,211774,5.108682,2.823710,73.063527,44.835203,31.973919,14.559803,11.406046,3.748325,6.086167,Ryotaro Taguchi,NaN,20000630,U,JPN
12714,211776,2.500000,3.000000,56.500000,35.000000,20.500000,7.000000,8.000000,4.500000,9.000000,Martin Landaluce,191.0,20060108,R,ESP
12715,212813,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,Kentaro Otsuka,NaN,<NA>,U,JPN
12716,212814,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,Naoya KOMODA,NaN,<NA>,U,JPN

In [50]:
# load node features
node_features = sorted_df[['ace','df','svpt','1stIn','1stWon','2ndWon', 'SvGms','bpSaved','bpFaced','height','dob','hand']]

node_features

,ace,df,svpt,1stIn,1stWon,2ndWon,SvGms,bpSaved,bpFaced,height,dob,hand
0,7.575835,3.880909,77.882098,49.684914,36.507129,14.191667,12.486935,3.564218,5.884390,198.0,19970420,R
1,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,193.0,19600227,L
2,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,188.0,19660702,R
3,0.000000,5.000000,90.000000,51.000000,31.000000,18.000000,10.000000,10.000000,14.000000,NaN,19661110,R
4,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,185.0,19661215,R
...,...,...,...,...,...,...,...,...,...,...,...,...
12712,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,NaN,<NA>,U
12713,5.108682,2.823710,73.063527,44.835203,31.973919,14.559803,11.406046,3.748325,6.086167,NaN,20000630,U
12714,2.500000,3.000000,56.500000,35.000000,20.500000,7.000000,8.000000,4.500000,9.000000,191.0,20060108,R
12715,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,NaN,<NA>,U
12716,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,NaN,<NA>,U

In [51]:
#convert non-numeric vals/one hot encoding for dominant hand

pd.set_option('mode.chained_assignment', None)
#handness = node_features["hand"].str.split(",", expand=True)
hands = pd.get_dummies(node_features.hand, dtype=int)

node_features = pd.concat([node_features, hands], axis='columns')
node_features.drop(["hand"], axis='columns', inplace=True)

In [52]:
# transforming dob into an age and filling missing values

node_features['age'] = 2026 - pd.to_datetime(node_features['dob'].astype(str), format='%Y%m%d', errors='coerce').dt.year
node_features['age'] = node_features['age'].fillna(node_features['age'].mean())
node_features['height'] = node_features['height'].fillna(node_features['height'].mean())
node_features = node_features.drop(['dob'], axis=1)
node_features

,ace,df,svpt,1stIn,1stWon,2ndWon,SvGms,bpSaved,bpFaced,height,A,L,R,U,age
0,7.575835,3.880909,77.882098,49.684914,36.507129,14.191667,12.486935,3.564218,5.884390,198.000000,0,0,1,0,29.000000
1,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,193.000000,0,1,0,0,66.000000
2,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,188.000000,0,0,1,0,60.000000
3,0.000000,5.000000,90.000000,51.000000,31.000000,18.000000,10.000000,10.000000,14.000000,183.874139,0,0,1,0,60.000000
4,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,185.000000,0,0,1,0,60.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12712,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,183.874139,0,0,0,1,32.815917
12713,5.108682,2.823710,73.063527,44.835203,31.973919,14.559803,11.406046,3.748325,6.086167,183.874139,0,0,0,1,26.000000
12714,2.500000,3.000000,56.500000,35.000000,20.500000,7.000000,8.000000,4.500000,9.000000,191.000000,0,0,1,0,20.000000
12715,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,183.874139,0,0,0,1,32.815917
12716,4.130268,3.327813,74.848836,45.131720,29.365498,13.441081,11.285491,4.553419,8.399145,183.874139,0,0,0,1,32.815917

In [53]:
sc = StandardScaler()
cols_to_scale = ['ace','df','svpt','1stIn','1stWon','2ndWon','SvGms','bpSaved','bpFaced','height','age']
node_features[cols_to_scale] = sc.fit_transform(node_features[cols_to_scale])

node_features

,ace,df,svpt,1stIn,1stWon,2ndWon,SvGms,bpSaved,bpFaced,height,A,L,R,U,age
0,3.381688,1.011747,0.863078,1.417194,2.089253,0.447848,1.703745,-1.194877,-1.858583,3.076321e+00,0,0,1,0,-5.583396e-01
1,-0.148743,0.140564,0.311357,0.239750,-0.017352,-0.044809,0.175442,0.458939,0.681829,1.987424e+00,0,1,0,0,4.855448e+00
2,-0.148743,0.140564,0.311357,0.239750,-0.017352,-0.044809,0.175442,0.458939,0.681829,8.985273e-01,0,0,1,0,3.977536e+00
3,-4.380742,2.774435,3.067206,1.757272,0.464785,2.947497,-1.459775,9.564915,6.339825,-6.189662e-15,0,0,1,0,3.977536e+00
4,-0.148743,0.140564,0.311357,0.239750,-0.017352,-0.044809,0.175442,0.458939,0.681829,2.451892e-01,0,0,1,0,3.977536e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12712,-0.148743,0.140564,0.311357,0.239750,-0.017352,-0.044809,0.175442,0.458939,0.681829,-6.189662e-15,0,0,0,1,1.039656e-15
12713,0.853769,-0.653452,-0.013373,0.163071,0.752067,0.689479,0.328794,-0.887073,-1.654747,-6.189662e-15,0,0,0,1,-9.972953e-01
12714,-1.819166,-0.375777,-3.026117,-2.380287,-2.632457,-4.272496,-4.003885,0.369630,1.288814,1.551865e+00,0,0,1,0,-1.875207e+00
12715,-0.148743,0.140564,0.311357,0.239750,-0.017352,-0.044809,0.175442,0.458939,0.681829,-6.189662e-15,0,0,0,1,1.039656e-15
12716,-0.148743,0.140564,0.311357,0.239750,-0.017352,-0.044809,0.175442,0.458939,0.681829,-6.189662e-15,0,0,0,1,1.039656e-15

In [54]:
# Convert to numpy
x = node_features.to_numpy()
print(x.shape)

(12717, 15)

In [55]:
# node index for players to be recognised by row
sorted_df = sorted_df.reset_index(drop=True)

player_id_to_idx = {
    player_id: idx
    for idx, player_id in enumerate(sorted_df['player_id'])
}

print(player_id_to_idx)
print(len(player_id_to_idx))

{100644: 0, 100653: 1, 101266: 2, 101305: 3, 101316: 4, 101339: 5, 101389: 6, 101404: 7, 101481: 8, 101492: 9, 101495: 10, 101509: 11, 101532: 12, 101535: 13, 101543: 14, 101549: 15, 101662: 16, 101723: 17, 101736: 18, 101746: 19, 101750: 20, 101772: 21, 101774: 22, 101775: 23, 101779: 24, 101790: 25, 101806: 26, 101810: 27, 101820: 28, 101855: 29, 101868: 30, 101869: 31, 101871: 32, 101885: 33, 101889: 34, 101895: 35, 101897: 36, 101924: 37, 101938: 38, 101947: 39, 101956: 40, 101960: 41, 101962: 42, 101964: 43, 101965: 44, 101976: 45, 101979: 46, 101990: 47, 101996: 48, 102021: 49, 102023: 50, 102031: 51, 102033: 52, 102035: 53, 102055: 54, 102060: 55, 102061: 56, 102076: 57, 102077: 58, 102087: 59, 102093: 60, 102100: 61, 102106: 62, 102107: 63, 102110: 64, 102123: 65, 102131: 66, 102143: 67, 102148: 68, 102167: 69, 102169: 70, 102179: 71, 102184: 72, 102202: 73, 102207: 74, 102223: 75, 102227: 76, 102231: 77, 102233: 78, 102234: 79, 102240: 80, 102243: 81, 102247: 82, 102250: 83, 102254: 84, 102257: 85, 102259: 86, 102267: 87, 102269: 88, 102271: 89, 102282: 90, 102286: 91, 102287: 92, 102300: 93, 102306: 94, 102314: 95, 102318: 96, 102320: 97, 102338: 98, 102344: 99, 102345: 100, 102358: 101, 102362: 102, 102369: 103, 102374: 104, 102381: 105, 102382: 106, 102384: 107, 102388: 108, 102401: 109, 102405: 110, 102406: 111, 102425: 112, 102431: 113, 102434: 114, 102437: 115, 102447: 116, 102450: 117, 102456: 118, 102457: 119, 102463: 120, 102464: 121, 102469: 122, 102473: 123, 102477: 124, 102494: 125, 102496: 126, 102497: 127, 102506: 128, 102512: 129, 102521: 130, 102529: 131, 102538: 132, 102539: 133, 102545: 134, 102548: 135, 102554: 136, 102556: 137, 102558: 138, 102562: 139, 102563: 140, 102565: 141, 102567: 142, 102571: 143, 102574: 144, 102579: 145, 102585: 146, 102595: 147, 102607: 148, 102610: 149, 102615: 150, 102617: 151, 102630: 152, 102642: 153, 102644: 154, 102652: 155, 102655: 156, 102659: 157, 102667: 158, 102678: 159, 102687: 160, 102690: 161, 102692: 162, 102694: 163, 102696: 164, 102701: 165, 102703: 166, 102706: 167, 102720: 168, 102721: 169, 102722: 170, 102730: 171, 102731: 172, 102737: 173, 102740: 174, 102765: 175, 102768: 176, 102770: 177, 102772: 178, 102774: 179, 102776: 180, 102780: 181, 102783: 182, 102785: 183, 102788: 184, 102789: 185, 102796: 186, 102800: 187, 102802: 188, 102811: 189, 102812: 190, 102818: 191, 102820: 192, 102821: 193, 102822: 194, 102826: 195, 102828: 196, 102830: 197, 102831: 198, 102834: 199, 102836: 200, 102839: 201, 102840: 202, 102842: 203, 102843: 204, 102845: 205, 102851: 206, 102854: 207, 102855: 208, 102856: 209, 102858: 210, 102860: 211, 102863: 212, 102864: 213, 102869: 214, 102873: 215, 102880: 216, 102881: 217, 102882: 218, 102885: 219, 102886: 220, 102887: 221, 102896: 222, 102902: 223, 102904: 224, 102905: 225, 102910: 226, 102911: 227, 102925: 228, 102928: 229, 102932: 230, 102934: 231, 102940: 232, 102945: 233, 102950: 234, 102956: 235, 102957: 236, 102959: 237, 102960: 238, 102961: 239, 102962: 240, 102963: 241, 102965: 242, 102967: 243, 102968: 244, 102969: 245, 102979: 246, 102982: 247, 102983: 248, 102985: 249, 102987: 250, 102997: 251, 102998: 252, 102999: 253, 103007: 254, 103009: 255, 103017: 256, 103018: 257, 103020: 258, 103029: 259, 103032: 260, 103033: 261, 103035: 262, 103037: 263, 103039: 264, 103043: 265, 103046: 266, 103047: 267, 103050: 268, 103052: 269, 103053: 270, 103060: 271, 103063: 272, 103065: 273, 103066: 274, 103076: 275, 103077: 276, 103080: 277, 103082: 278, 103084: 279, 103088: 280, 103096: 281, 103101: 282, 103103: 283, 103104: 284, 103105: 285, 103109: 286, 103110: 287, 103114: 288, 103118: 289, 103119: 290, 103125: 291, 103133: 292, 103145: 293, 103147: 294, 103149: 295, 103151: 296, 103153: 297, 103154: 298, 103157: 299, 103163: 300, 103165: 301, 103166: 302, 103168: 303, 103169: 304, 103171: 305, 103174: 306, 103175: 307, 103176: 308, 103178: 309, 103181: 310, 103182: 311, 103184: 312, 103185: 313, 103188: 314, 103190: 315, 103193: 316, 103197: 317, 103198: 318, 103201: 319, 103202: 320, 103204: 321, 103205: 322, 103206: 323, 103208: 324, 103209: 325, 103213: 326, 103218: 327, 103220: 328, 103222: 329, 103225: 330, 103226: 331, 103228: 332, 103229: 333, 103230: 334, 103238: 335, 103239: 336, 103240: 337, 103242: 338, 103248: 339, 103250: 340, 103252: 341, 103254: 342, 103259: 343, 103264: 344, 103268: 345, 103273: 346, 103280: 347, 103281: 348, 103285: 349, 103286: 350, 103287: 351, 103288: 352, 103290: 353, 103292: 354, 103294: 355, 103296: 356, 103297: 357, 103303: 358, 103305: 359, 103316: 360, 103318: 361, 103319: 362, 103321: 363, 103324: 364, 103325: 365, 103327: 366, 103328: 367, 103331: 368, 103333: 369, 103334: 370, 103336: 371, 103337: 372, 103339: 373, 103344: 374, 103350: 375, 103353: 376, 103355: 377, 103356: 378, 103363: 379, 103365: 380, 103369: 381, 103371: 382, 103373: 383, 103385: 384, 103387: 385, 103390: 386, 103393: 387, 103395: 388, 103397: 389, 103401: 390, 103402: 391, 103403: 392, 103407: 393, 103408: 394, 103409: 395, 103410: 396, 103413: 397, 103417: 398, 103419: 399, 103420: 400, 103421: 401, 103422: 402, 103424: 403, 103425: 404, 103427: 405, 103428: 406, 103429: 407, 103435: 408, 103437: 409, 103439: 410, 103444: 411, 103447: 412, 103448: 413, 103451: 414, 103453: 415, 103454: 416, 103455: 417, 103459: 418, 103460: 419, 103465: 420, 103467: 421, 103468: 422, 103470: 423, 103472: 424, 103478: 425, 103483: 426, 103484: 427, 103487: 428, 103488: 429, 103490: 430, 103492: 431, 103493: 432, 103498: 433, 103499: 434, 103501: 435, 103503: 436, 103504: 437, 103505: 438, 103506: 439, 103507: 440, 103510: 441, 103514: 442, 103516: 443, 103520: 444, 103521: 445, 103523: 446, 103524: 447, 103525: 448, 103527: 449, 103528: 450, 103529: 451, 103530: 452, 103531: 453, 103534: 454, 103535: 455, 103538: 456, 103540: 457, 103541: 458, 103543: 459, 103544: 460, 103549: 461, 103552: 462, 103553: 463, 103556: 464, 103558: 465, 103559: 466, 103560: 467, 103563: 468, 103565: 469, 103566: 470, 103568: 471, 103573: 472, 103574: 473, 103577: 474, 103580: 475, 103581: 476, 103582: 477, 103586: 478, 103587: 479, 103590: 480, 103592: 481, 103594: 482, 103598: 483, 103599: 484, 103600: 485, 103602: 486, 103607: 487, 103608: 488, 103609: 489, 103611: 490, 103612: 491, 103617: 492, 103620: 493, 103621: 494, 103623: 495, 103626: 496, 103630: 497, 103631: 498, 103632: 499, 103636: 500, 103637: 501, 103638: 502, 103639: 503, 103641: 504, 103643: 505, 103646: 506, 103647: 507, 103650: 508, 103651: 509, 103653: 510, 103655: 511, 103656: 512, 103657: 513, 103659: 514, 103662: 515, 103663: 516, 103665: 517, 103666: 518, 103668: 519, 103669: 520, 103670: 521, 103672: 522, 103673: 523, 103674: 524, 103675: 525, 103676: 526, 103682: 527, 103684: 528, 103687: 529, 103689: 530, 103690: 531, 103691: 532, 103693: 533, 103694: 534, 103695: 535, 103697: 536, 103699: 537, 103700: 538, 103701: 539, 103702: 540, 103704: 541, 103708: 542, 103709: 543, 103711: 544, 103714: 545, 103716: 546, 103718: 547, 103720: 548, 103722: 549, 103723: 550, 103724: 551, 103726: 552, 103727: 553, 103728: 554, 103730: 555, 103734: 556, 103735: 557, 103736: 558, 103737: 559, 103739: 560, 103742: 561, 103744: 562, 103746: 563, 103747: 564, 103748: 565, 103750: 566, 103752: 567, 103754: 568, 103756: 569, 103758: 570, 103760: 571, 103761: 572, 103762: 573, 103763: 574, 103770: 575, 103772: 576, 103775: 577, 103776: 578, 103777: 579, 103780: 580, 103781: 581, 103782: 582, 103783: 583, 103786: 584, 103788: 585, 103789: 586, 103794: 587, 103799: 588, 103801: 589, 103802: 590, 103803: 591, 103805: 592, 103806: 593, 103808: 594, 103811: 595, 103812: 596, 103813: 597, 103814: 598, 103815: 599, 103817: 600, 103819: 601, 103820: 602, 103821: 603, 103822: 604, 103823: 605, 103824: 606, 103826: 607, 103827: 608, 103828: 609, 103829: 610, 103830: 611, 103831: 612, 103833: 613, 103834: 614, 103835: 615, 103837: 616, 103838: 617, 103841: 618, 103843: 619, 103847: 620, 103849: 621, 103850: 622, 103851: 623, 103852: 624, 103855: 625, 103857: 626, 103858: 627, 103859: 628, 103860: 629, 103861: 630, 103863: 631, 103864: 632, 103865: 633, 103867: 634, 103868: 635, 103870: 636, 103871: 637, 103872: 638, 103875: 639, 103876: 640, 103877: 641, 103878: 642, 103882: 643, 103886: 644, 103888: 645, 103891: 646, 103893: 647, 103894: 648, 103897: 649, 103898: 650, 103899: 651, 103900: 652, 103902: 653, 103905: 654, 103908: 655, 103909: 656, 103912: 657, 103913: 658, 103914: 659, 103916: 660, 103917: 661, 103919: 662, 103920: 663, 103921: 664, 103923: 665, 103924: 666, 103925: 667, 103926: 668, 103929: 669, 103932: 670, 103934: 671, 103936: 672, 103937: 673, 103938: 674, 103945: 675, 103946: 676, 103947: 677, 103948: 678, 103949: 679, 103953: 680, 103955: 681, 103956: 682, 103958: 683, 103959: 684, 103962: 685, 103963: 686, 103964: 687, 103967: 688, 103969: 689, 103970: 690, 103971: 691, 103973: 692, 103975: 693, 103976: 694, 103977: 695, 103978: 696, 103980: 697, 103981: 698, 103984: 699, 103986: 700, 103987: 701, 103990: 702, 103992: 703, 103993: 704, 103994: 705, 103997: 706, 103998: 707, 103999: 708, 104000: 709, 104001: 710, 104003: 711, 104004: 712, 104006: 713, 104007: 714, 104008: 715, 104010: 716, 104011: 717, 104013: 718, 104014: 719, 104015: 720, 104016: 721, 104019: 722, 104020: 723, 104021: 724, 104022: 725, 104023: 726, 104025: 727, 104026: 728, 104027: 729, 104028: 730, 104029: 731, 104030: 732, 104031: 733, 104033: 734, 104034: 735, 104035: 736, 104036: 737, 104037: 738, 104038: 739, 104040: 740, 104043: 741, 104044: 742, 104045: 743, 104046: 744, 104047: 745, 104049: 746, 104051: 747, 104052: 748, 104053: 749, 104054: 750, 104056: 751, 104057: 752, 104058: 753, 104059: 754, 104063: 755, 104065: 756, 104067: 757, 104068: 758, 104070: 759, 104071: 760, 104075: 761, 104076: 762, 104079: 763, 104080: 764, 104081: 765, 104082: 766, 104083: 767, 104084: 768, 104086: 769, 104091: 770, 104093: 771, 104095: 772, 104097: 773, 104098: 774, 104099: 775, 104101: 776, 104103: 777, 104104: 778, 104106: 779, 104112: 780, 104113: 781, 104115: 782, 104117: 783, 104121: 784, 104122: 785, 104126: 786, 104127: 787, 104128: 788, 104129: 789, 104131: 790, 104132: 791, 104136: 792, 104138: 793, 104140: 794, 104141: 795, 104145: 796, 104146: 797, 104148: 798, 104149: 799, 104151: 800, 104152: 801, 104154: 802, 104155: 803, 104158: 804, 104159: 805, 104160: 806, 104161: 807, 104162: 808, 104163: 809, 104165: 810, 104166: 811, 104167: 812, 104168: 813, 104171: 814, 104173: 815, 104176: 816, 104178: 817, 104179: 818, 104180: 819, 104181: 820, 104182: 821, 104183: 822, 104184: 823, 104186: 824, 104187: 825, 104188: 826, 104190: 827, 104191: 828, 104192: 829, 104195: 830, 104196: 831, 104198: 832, 104200: 833, 104201: 834, 104204: 835, 104206: 836, 104208: 837, 104209: 838, 104210: 839, 104211: 840, 104212: 841, 104213: 842, 104214: 843, 104215: 844, 104216: 845, 104217: 846, 104219: 847, 104220: 848, 104221: 849, 104222: 850, 104223: 851, 104224: 852, 104225: 853, 104226: 854, 104227: 855, 104228: 856, 104229: 857, 104230: 858, 104233: 859, 104234: 860, 104235: 861, 104236: 862, 104238: 863, 104240: 864, 104241: 865, 104244: 866, 104245: 867, 104246: 868, 104247: 869, 104249: 870, 104250: 871, 104251: 872, 104252: 873, 104253: 874, 104254: 875, 104256: 876, 104257: 877, 104258: 878, 104259: 879, 104260: 880, 104261: 881, 104262: 882, 104264: 883, 104265: 884, 104266: 885, 104267: 886, 104268: 887, 104269: 888, 104270: 889, 104272: 890, 104273: 891, 104274: 892, 104275: 893, 104276: 894, 104278: 895, 104280: 896, 104281: 897, 104283: 898, 104284: 899, 104285: 900, 104286: 901, 104287: 902, 104288: 903, 104290: 904, 104291: 905, 104292: 906, 104293: 907, 104294: 908, 104295: 909, 104297: 910, 104298: 911, 104299: 912, 104305: 913, 104306: 914, 104308: 915, 104311: 916, 104312: 917, 104314: 918, 104315: 919, 104316: 920, 104317: 921, 104319: 922, 104320: 923, 104323: 924, 104324: 925, 104325: 926, 104327: 927, 104328: 928, 104330: 929, 104331: 930, 104332: 931, 104334: 932, 104336: 933, 104338: 934, 104339: 935, 104342: 936, 104344: 937, 104347: 938, 104348: 939, 104349: 940, 104352: 941, 104353: 942, 104354: 943, 104355: 944, 104356: 945, 104357: 946, 104358: 947, 104359: 948, 104360: 949, 104361: 950, 104362: 951, 104363: 952, 104365: 953, 104366: 954, 104368: 955, 104371: 956, 104372: 957, 104373: 958, 104374: 959, 104375: 960, 104377: 961, 104378: 962, 104379: 963, 104380: 964, 104381: 965, 104383: 966, 104384: 967, 104385: 968, 104386: 969, 104387: 970, 104388: 971, 104390: 972, 104391: 973, 104392: 974, 104393: 975, 104394: 976, 104395: 977, 104397: 978, 104398: 979, 104399: 980, 104402: 981, 104405: 982, 104407: 983, 104410: 984, 104412: 985, 104415: 986, 104417: 987, 104421: 988, 104423: 989, 104424: 990, 104425: 991, 104426: 992, 104428: 993, 104431: 994, 104432: 995, 104433: 996, 104434: 997, 104435: 998, 104436: 999, 104437: 1000, 104438: 1001, 104439: 1002, 104441: 1003, 104442: 1004, 104444: 1005, 104445: 1006, 104446: 1007, 104451: 1008, 104452: 1009, 104453: 1010, 104454: 1011, 104455: 1012, 104456: 1013, 104458: 1014, 104460: 1015, 104461: 1016, 104463: 1017, 104464: 1018, 104465: 1019, 104467: 1020, 104468: 1021, 104469: 1022, 104470: 1023, 104471: 1024, 104472: 1025, 104473: 1026, 104474: 1027, 104476: 1028, 104477: 1029, 104478: 1030, 104479: 1031, 104480: 1032, 104481: 1033, 104484: 1034, 104485: 1035, 104486: 1036, 104487: 1037, 104488: 1038, 104489: 1039, 104490: 1040, 104491: 1041, 104492: 1042, 104494: 1043, 104495: 1044, 104496: 1045, 104497: 1046, 104498: 1047, 104499: 1048, 104500: 1049, 104501: 1050, 104502: 1051, 104503: 1052, 104504: 1053, 104505: 1054, 104506: 1055, 104508: 1056, 104509: 1057, 104510: 1058, 104512: 1059, 104513: 1060, 104514: 1061, 104515: 1062, 104516: 1063, 104517: 1064, 104518: 1065, 104519: 1066, 104522: 1067, 104523: 1068, 104524: 1069, 104525: 1070, 104526: 1071, 104527: 1072, 104528: 1073, 104531: 1074, 104532: 1075, 104534: 1076, 104535: 1077, 104538: 1078, 104540: 1079, 104541: 1080, 104542: 1081, 104543: 1082, 104544: 1083, 104545: 1084, 104546: 1085, 104547: 1086, 104548: 1087, 104550: 1088, 104551: 1089, 104553: 1090, 104554: 1091, 104555: 1092, 104556: 1093, 104557: 1094, 104558: 1095, 104559: 1096, 104560: 1097, 104561: 1098, 104562: 1099, 104563: 1100, 104565: 1101, 104566: 1102, 104567: 1103, 104569: 1104, 104571: 1105, 104572: 1106, 104574: 1107, 104576: 1108, 104578: 1109, 104579: 1110, 104580: 1111, 104581: 1112, 104582: 1113, 104583: 1114, 104585: 1115, 104586: 1116, 104587: 1117, 104589: 1118, 104590: 1119, 104591: 1120, 104592: 1121, 104593: 1122, 104594: 1123, 104595: 1124, 104597: 1125, 104598: 1126, 104600: 1127, 104601: 1128, 104602: 1129, 104603: 1130, 104604: 1131, 104605: 1132, 104606: 1133, 104607: 1134, 104608: 1135, 104609: 1136, 104610: 1137, 104611: 1138, 104612: 1139, 104613: 1140, 104615: 1141, 104618: 1142, 104619: 1143, 104620: 1144, 104621: 1145, 104622: 1146, 104623: 1147, 104625: 1148, 104627: 1149, 104628: 1150, 104629: 1151, 104630: 1152, 104631: 1153, 104633: 1154, 104635: 1155, 104636: 1156, 104637: 1157, 104638: 1158, 104639: 1159, 104640: 1160, 104641: 1161, 104643: 1162, 104644: 1163, 104646: 1164, 104647: 1165, 104651: 1166, 104652: 1167, 104654: 1168, 104655: 1169, 104656: 1170, 104658: 1171, 104659: 1172, 104660: 1173, 104661: 1174, 104662: 1175, 104664: 1176, 104665: 1177, 104666: 1178, 104667: 1179, 104668: 1180, 104669: 1181, 104672: 1182, 104673: 1183, 104674: 1184, 104675: 1185, 104676: 1186, 104677: 1187, 104678: 1188, 104679: 1189, 104680: 1190, 104681: 1191, 104682: 1192, 104683: 1193, 104684: 1194, 104685: 1195, 104687: 1196, 104688: 1197, 104689: 1198, 104690: 1199, 104692: 1200, 104693: 1201, 104694: 1202, 104695: 1203, 104696: 1204, 104697: 1205, 104698: 1206, 104699: 1207, 104700: 1208, 104701: 1209, 104702: 1210, 104704: 1211, 104705: 1212, 104707: 1213, 104708: 1214, 104709: 1215, 104712: 1216, 104713: 1217, 104714: 1218, 104715: 1219, 104716: 1220, 104717: 1221, 104718: 1222, 104719: 1223, 104720: 1224, 104721: 1225, 104722: 1226, 104723: 1227, 104724: 1228, 104725: 1229, 104727: 1230, 104728: 1231, 104729: 1232, 104730: 1233, 104731: 1234, 104732: 1235, 104733: 1236, 104735: 1237, 104736: 1238, 104737: 1239, 104738: 1240, 104739: 1241, 104740: 1242, 104741: 1243, 104743: 1244, 104744: 1245, 104745: 1246, 104746: 1247, 104749: 1248, 104750: 1249, 104752: 1250, 104753: 1251, 104755: 1252, 104756: 1253, 104757: 1254, 104758: 1255, 104760: 1256, 104761: 1257, 104763: 1258, 104764: 1259, 104765: 1260, 104766: 1261, 104768: 1262, 104769: 1263, 104770: 1264, 104771: 1265, 104772: 1266, 104773: 1267, 104775: 1268, 104777: 1269, 104778: 1270, 104779: 1271, 104780: 1272, 104781: 1273, 104783: 1274, 104784: 1275, 104785: 1276, 104786: 1277, 104789: 1278, 104790: 1279, 104791: 1280, 104792: 1281, 104793: 1282, 104797: 1283, 104798: 1284, 104799: 1285, 104800: 1286, 104801: 1287, 104802: 1288, 104803: 1289, 104804: 1290, 104805: 1291, 104807: 1292, 104808: 1293, 104809: 1294, 104810: 1295, 104811: 1296, 104812: 1297, 104813: 1298, 104814: 1299, 104815: 1300, 104816: 1301, 104817: 1302, 104818: 1303, 104819: 1304, 104820: 1305, 104821: 1306, 104822: 1307, 104823: 1308, 104824: 1309, 104826: 1310, 104827: 1311, 104828: 1312, 104829: 1313, 104830: 1314, 104831: 1315, 104832: 1316, 104833: 1317, 104834: 1318, 104835: 1319, 104836: 1320, 104838: 1321, 104839: 1322, 104840: 1323, 104841: 1324, 104842: 1325, 104843: 1326, 104844: 1327, 104846: 1328, 104847: 1329, 104848: 1330, 104850: 1331, 104851: 1332, 104852: 1333, 104853: 1334, 104854: 1335, 104855: 1336, 104856: 1337, 104857: 1338, 104858: 1339, 104859: 1340, 104861: 1341, 104862: 1342, 104863: 1343, 104864: 1344, 104865: 1345, 104866: 1346, 104867: 1347, 104868: 1348, 104869: 1349, 104870: 1350, 104871: 1351, 104873: 1352, 104874: 1353, 104875: 1354, 104877: 1355, 104878: 1356, 104879: 1357, 104880: 1358, 104881: 1359, 104882: 1360, 104883: 1361, 104884: 1362, 104887: 1363, 104888: 1364, 104890: 1365, 104892: 1366, 104893: 1367, 104895: 1368, 104896: 1369, 104897: 1370, 104898: 1371, 104899: 1372, 104900: 1373, 104901: 1374, 104903: 1375, 104905: 1376, 104906: 1377, 104907: 1378, 104908: 1379, 104909: 1380, 104910: 1381, 104911: 1382, 104912: 1383, 104914: 1384, 104915: 1385, 104916: 1386, 104917: 1387, 104918: 1388, 104919: 1389, 104920: 1390, 104921: 1391, 104922: 1392, 104923: 1393, 104924: 1394, 104925: 1395, 104926: 1396, 104927: 1397, 104928: 1398, 104929: 1399, 104930: 1400, 104931: 1401, 104932: 1402, 104933: 1403, 104934: 1404, 104935: 1405, 104936: 1406, 104937: 1407, 104938: 1408, 104939: 1409, 104940: 1410, 104942: 1411, 104944: 1412, 104945: 1413, 104946: 1414, 104947: 1415, 104948: 1416, 104949: 1417, 104950: 1418, 104951: 1419, 104952: 1420, 104953: 1421, 104956: 1422, 104957: 1423, 104958: 1424, 104960: 1425, 104961: 1426, 104962: 1427, 104963: 1428, 104965: 1429, 104967: 1430, 104969: 1431, 104970: 1432, 104971: 1433, 104972: 1434, 104973: 1435, 104974: 1436, 104975: 1437, 104976: 1438, 104977: 1439, 104978: 1440, 104979: 1441, 104980: 1442, 104981: 1443, 104982: 1444, 104983: 1445, 104984: 1446, 104985: 1447, 104986: 1448, 104987: 1449, 104988: 1450, 104989: 1451, 104990: 1452, 104991: 1453, 104992: 1454, 104993: 1455, 104994: 1456, 104995: 1457, 104996: 1458, 104997: 1459, 104998: 1460, 104999: 1461, 105000: 1462, 105001: 1463, 105002: 1464, 105003: 1465, 105004: 1466, 105005: 1467, 105006: 1468, 105008: 1469, 105009: 1470, 105011: 1471, 105012: 1472, 105014: 1473, 105015: 1474, 105016: 1475, 105018: 1476, 105020: 1477, 105022: 1478, 105023: 1479, 105024: 1480, 105025: 1481, 105026: 1482, 105027: 1483, 105028: 1484, 105029: 1485, 105030: 1486, 105031: 1487, 105032: 1488, 105033: 1489, 105034: 1490, 105036: 1491, 105037: 1492, 105038: 1493, 105039: 1494, 105040: 1495, 105041: 1496, 105042: 1497, 105043: 1498, 105044: 1499, 105045: 1500, 105046: 1501, 105047: 1502, 105048: 1503, 105050: 1504, 105051: 1505, 105052: 1506, 105053: 150

Edges For Graphs

In [56]:
#
edge_source = historical_df['winner_id'].map(player_id_to_idx).values
edge_target = historical_df['loser_id'].map(player_id_to_idx).values

edge_index_np = np.stack([edge_source, edge_target],axis=0)
edge_index = torch.tensor(edge_index_np, dtype=torch.long)
print(edge_index.shape)

torch.Size([2, 372133])

In [57]:
# build data object
data = Data(x=x, edge_index=edge_index)
print(data)

Data(x=[12717, 15], edge_index=[2, 372133])

In [58]:
from torch_geometric.transforms import ToUndirected
data = ToUndirected()(data)

data

Data(x=[12717, 15], edge_index=[2, 555189])

In [59]:
import torch_geometric.transforms as T

transform = T.RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    add_negative_train_samples=True,
    neg_sampling_ratio=1.0,
)
train_data, val_data, test_data = transform(data)

print(train_data)
print(val_data)
print(test_data)

Data(x=[12717, 15], edge_index=[2, 444156], edge_label=[444156], edge_label_index=[2, 444156])
Data(x=[12717, 15], edge_index=[2, 444156], edge_label=[55518], edge_label_index=[2, 55518])
Data(x=[12717, 15], edge_index=[2, 499674], edge_label=[55518], edge_label_index=[2, 55518])

In [60]:
# saving data to be used on gnn
torch.save(data, 'atp_graph.pt')
torch.save(train_data, 'train_data.pt')
torch.save(val_data, 'val_data.pt')
torch.save(test_data, 'test_data.pt')